// basededatos.js
export const baseDeDatos = [
    { codigoPostal: "08000", colonia: "Gabriel Ramos Millán Sección Bramadero", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08010", colonia: "Ex-Ejido de La Magdalena Mixiuhca", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08020", colonia: "Ampliación Gabriel Ramos Millán", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08030", colonia: "Gabriel Ramos Millán Sección Cuchilla", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08040", colonia: "Carlos Zapata Vela", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08100", colonia: "Agrícola Pantitlán", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08200", colonia: "Viaducto Piedad", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08210", colonia: "Nueva Santa Anita", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08220", colonia: "Barrio San Pedro", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08230", colonia: "Barrio San Francisco Xicaltongo", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08240", colonia: "Barrio Santiago Norte", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08300", colonia: "Santa Anita", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08310", colonia: "La Cruz", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08320", colonia: "Fraccionamiento Coyuya", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08400", colonia: "Granjas México", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08420", colonia: "Cuchilla Agrícola Oriental", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08500", colonia: "Agrícola Oriental", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08510", colonia: "El Rodeo", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08600", colonia: "Barrio La Asunción", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08610", colonia: "Barrio Zapotla", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08620", colonia: "Barrio Los Reyes", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08650", colonia: "Barrio San Miguel", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08700", colonia: "Juventino Rosas", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08710", colonia: "Tlazintla", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08720", colonia: "Gabriel Ramos Millán Sección Tlacotal", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08730", colonia: "Gabriel Ramos Millán", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08760", colonia: "INPI Picos", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08760", colonia: "Los Picos de Iztacalco Sección 2A", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08760", colonia: "Los Picos de Iztacalco Sección 1B", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08770", colonia: "Los Picos de Iztacalco Sección 1A", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08800", colonia: "Santiago Sur", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08810", colonia: "Reforma Iztaccíhuatl Norte", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08830", colonia: "Militar Marte", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08840", colonia: "Reforma Iztaccíhuatl Sur", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08900", colonia: "INFONAVIT Iztacalco", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08910", colonia: "Santa Cruz", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08920", colonia: "Jardines Tecma", municipio: "Iztacalco", estado: "Ciudad de México" },
    { codigoPostal: "08930", colonia: "Campamento 2 de Octubre", municipio: "Iztacalco", estado: "Ciudad de México" },
];

export const codigosPostales = Array.from(new Set(baseDeDatos.map(entry => entry.codigoPostal)));
